export const icons = {
  bookmark: require('../assets/icons/bookmark.png'),
  bookmarkFilled: require('../assets/icons/bookmark-filled.png'),
  home: require('../assets/icons/home.png'),
  search: require('../assets/icons/search.png'),
  settings: require('../assets/icons/settings.png'),
  back: require('../assets/icons/back.png'),
  rightArrow: require('../assets/icons/right-arrow.png'),
  plus: require('../assets/icons/plus.png'),
  threeDots: require('../assets/icons/three_dots.png'),
  openEye: require('../assets/icons/open_eye.png'),
  gallery: require('../assets/icons/gallery.png'),
  checkmarkGreen: require('../assets/icons/checkmark_green.png'),
  reset: require('../assets/icons/reset.png'),
  trash: require('../assets/icons/trash.png'),
  close: require('../assets/icons/close.png'),
  close_circle: require('../assets/icons/close-circle.png'),
  no_results: require('../assets/icons/no_results.png'),

  abstract_shape1: require('../assets/icons/abstract-shape.png'),
};
